### ISSUE TITLE
无障碍服务里没有戳戳乐

### ISSUE THREAD

**Issue by Miuzarte** [IcebemAst/ArknightsTap#25]
![Screenshot_2021-02-09-09-21-52-667_com android settings](https://user-images.githubusercontent.com/66856838/107302491-186bc080-6a43-11eb-907b-0758470f41de.jpg)
开启了戳戳乐功能但是无障碍服务里没有
（我是备份了应用数据开的Originium）

**Comment by aistra0528** [comment]
重新解除一次封印
