### ISSUE TITLE
crdroid下无法使用戳戳乐

### ISSUE THREAD

**Issue by aisuneko** [IcebemAst/ArknightsTap#26]
如图，screen reader一项下没有任何显示，无法给应用开启无障碍服务
重新解除封印后问题依旧
![Screenshot_20210306-203006_Settings](https://user-images.githubusercontent.com/22784008/110206791-d5becc00-7eba-11eb-987c-c9acbe84584b.png)

**Comment by aistra0528** [comment]
重启手机了吗

**Comment by aisuneko** [comment]
已重启多次
