### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [IcebemAst/ArknightsTap#31]
请问是否可以将应用发布到 F-Droid？谢谢！

**Comment by aistra0528** [comment]
可以的，但我可能没什么精力管

**Comment by linsui** [comment]
谢谢，我会打包提交，后续更新是自动的。

**Comment by linsui** [comment]
我开了一个[合并请求](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10580)。稍后在这边提交一个 PR 添加 F-Droid 要求的 fastlane 元数据。

**Comment by linsui** [comment]
已合并，感谢你的帮助和支持！应用会在两到三天内进入存储库。F-Droid 的徽标

[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/com.icebem.akt)

```
[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/com.icebem.akt)
```
