### ISSUE TITLE
关于 Lis 版和 Originium 版

### ISSUE THREAD

**Issue by imaegoo** [IcebemAst/ArknightsTap#36]
我正在编写另一个无障碍服务应用。在参考本项目的代码实现时发现 `AndroidManifest.xml` 无障碍服务首先被声明为 `enabled="false"`，用户切换到 Originium 版本时 `PreferenceManager.kt` 才将服务 `setComponentEnabledSetting` 为 `true`，我从代码、issues、搜索引擎中没有找到这样做的原因，请问为什么要区分不带无障碍的版本和带无障碍的版本呢？如果直接声明 `enabled="true"` 会有什么问题？感谢作者解惑！

**Comment by aistra0528** [comment]
技术上没有任何问题。因为无障碍是敏感权限，不是所有人都会用到，所以方舟帮帮忙才会默认禁用。
